version: '3.9'

services:

  db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: andres_dev
      POSTGRES_PASSWORD: development
      POSTGRES_DB: sgd_ruminahui

  pgadmin:
    container_name: PGAdminDev
    image: dpage/pgadmin4
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: andres_dev@dev.com
      PGADMIN_DEFAULT_PASSWORD: development